### ISSUE TITLE
Publish artifacts in a Maven repo

### ISSUE THREAD

**Issue by mmazi** [CurrencyCloud/currencycloud-java#21]
This can be done automatically using Travis.

**Comment by mmazi** [comment]
Should we do this? If we don't, the users that use Maven (or (probably) Gradle etc.) will be required to build the project themselves, as currently described [in the README](https://github.com/CurrencyCloud/currencycloud-java#installation).

Publishing snapshots in a Maven Repo (Sonatype) can be done automatically by Travis.

Publishing releases requires:
* a bit of manual work for each release, 
* keeping the PGP keys that allow publishing.

**Comment by rjnienaber** [comment]
> Publishing snapshots in a Maven Repo (Sonatype) can be done automatically by Travis.

I think we would have a good start if we did this.

> Publishing final releases requires:

>    a bit of manual work for each release,
>    keeping the PGP keys that allow publishing.

I think we would need to do this in order to give confidence in the library. We'll try and follow the relevant guides ([OSSRH Guide](http://central.sonatype.org/pages/ossrh-guide.html) and [Releasing the Deployment](http://central.sonatype.org/pages/releasing-the-deployment.html)) and publish a 'release' version once a good level of functionality has been implemented.

**Comment by mmazi** [comment]
I'll provide some simpler instructions for what needs to be done to publish final releases.

**Comment by mmazi** [comment]
Some links:

[Securely storing sensitive data (eg. passwords, private keys) that Travis can access]
(http://docs.travis-ci.com/user/encryption-keys/)

[A helpful blog post]
(http://xeiam.com/configure-travis-ci-to-deploy-snapshots/)

**Comment by mmazi** [comment]
A clarification: Sonatype requires non-snapshot releases to be signed etc. (see #26), whereas snapshot builds don't need to meet these requirements. The plan is to publish unsigned snapshots automatically via Travis on every push (still with full javadocs and sources though, see #30), and to only sign final releases (see #31).
